name: news_book
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cloud_firestore: ^1.0.4
  cupertino_icons: ^1.0.2
  device_information: ^0.0.4
  dio: ^4.0.6
  dot_navigation_bar: ^1.0.1+4
  equatable: ^2.0.3
  firebase_auth: ^1.0.3
  firebase_core: ^1.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_login: ^3.0.0
  flutter_slidable: ^1.2.0
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.3.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  http: ^0.13.4
  multi_select_flutter: ^4.1.2
  shared_preferences: ^2.0.13
  toast: ^0.3.0
  webview_flutter: ^3.0.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.1.2
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/appicon.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#0e2050"
  image: assets/icons/newslogo.png

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
